project:
  type: website
  output-dir: docs

website:
  title: "Tive Khumalo"
  favicon: lab_favicon_small.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: people.qmd
        text: People
      - href: publications.qmd
        text: Publications
        menu:
          - href: https://winterstat.github.io/escp8082_rlabs
            text: ESCP 8082 Foundations of Measurement
          - href: https://winterstat.github.io/escp9710_rlabs
            text: ESCP 9710 Structural Equation Modeling
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/tive-khumalo-62240318b/?isSelfProfile=true
      - icon: github
        href: https://github.com/tivekhumalo
  back-to-top-navigation: true
  page-footer: "Copyright 2026, Tive B.P. Khumalo"
  twitter-card: true
  open-graph: true


format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: true
    link-external-newwindow: true

editor: visual

